[package]
name = "ic-e8s"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.10"
serde = "1.0"
lazy_static = "1.4"
num-bigint = "0.4"
